### PR TITLE
September 2021 Update

### PR DESCRIPTION
**Pull request by givenscj**
Latest updates, a final lab pass is needed to verify some changes in Azure.

### CODE REVIEW

**Review by idbanham — COMMENTED** [review]
In the Before the Lab section - either state which regions are valid in the list or remove the restrictions from the template.json. Why no EMEA or APAC regions in the list?

When initially logging into the oilwells-server (Exercise 1 task 1) it says connect via SSH on one line and then RDP on the next - confusing

Task 3 is already done for you

Exercise 2 Task 1 - Hyper-V Manager not console. VM is called UBUSRV, usefully it auto logs in as wsuser for step 5 you have to manually install the net-tools package. For UK users keyboard is swapped so you have to use " to get the @ symbol for the password. Also had to install SSH. 

Step 10 - as it's a stand alone Ubuntu VM you just SSH to it and run the commands.

Task 3 - the standalone Ubuntu VM is using S2admin as user not wsuser, so the script has to be modified for that VM

For the cmake command I had to run that prefixed with sudo as otherwise there were permission errors

Step 7 of task 5 comes way too late....

Exercise 4 task 1 - the command sudo apt-get install -y auditd audispd-plugins was already done in an earlier step.

Submitting now.... Hopefully will be able to add more later

**Review by idbanham — COMMENTED** [review]
Exercise 5 - This may be a Microsoft internal issue but the Microsoft Defender Portal looks different and just reports LOTS of "you don't have access" errors. This may be an issue for customers if they are using corporate accounts as they are unlikely to have access rights to these features either. Why are we using this rather than the AD 4 IoT Micro Agent? https://docs.microsoft.com/en-us/azure/defender-for-iot/device-builders/quickstart-standalone-agent-binary-installation

Exercise 6 task 2 - you need to state that content of the file that you copied needs to be saved as a file called <whatever>.pem 

Exercise 6 Task 2 step 14 - to get this to work I had to add the IP Address of the Oilwells-server-<init> to the firewall rules on oilwells-do1-<init>

**Review by idbanham — COMMENTED** [review]
Unfortunately I've hit a brick wall... In exercise 2 there was only one VM in my Hyper-V session, so I used that for Edge and used the Azure VM oilwells-d01 for the device... 

The result of this is that I can't do Exercise 6, task 4 step 17 and beyond because the VM running Edge has no public IP of it's own so the d01 azure VM can't see it. I've tried to get a public IP for it an managed to break the networking completely.

I'm suspecting that there's something up in the config of the oilwells-server VM as I only got 1 VM in Hyper V and even that was named incorrectly.

As an overall comment for how far I've got, there's still a lot of set-up typing with not a lot of explanation of WHY you're doing a task. There's potential for some of this to be scripted, stored in git and downloaded via a wget command and just run. 

The options to run different versions of IoT Edge and choices as to whether to run hardware/software TPS are nice, but it adds quite a bit of complexity to the workshop. Shouldn't we really encourage customers to go down the hardware route and explain what not doing this brings in terms of security risk? 

The Solution architectures at the beginning don't add a lot, it would be better to have a diagram of what the workshop is actually going to build and maybe an explanation of why it's like this for the workshop and how the "real world" would differ from this. Adding in where the various certificates are located, what they're for and again what would differ in the real world would be useful.

**Comment by shailendramiglani** [comment]
Recommendation is to use the latest IoT Defender Agent https://docs.microsoft.com/en-us/azure/defender-for-iot/device-builders/quickstart-standalone-agent-binary-installation

**Comment by shailendramiglani** [comment]
Suggestion - Recommended to use IoT Edge version 1.2 and update MCW. Users will always adopt latest version of Edge and will find different commands if running 1.2. If not possible to change the IoT Edge version, then please specifically highlight in bold to use the specific version of Edge to run this workshop.

**Pull request merged**
